GET http://localhost:5000/api/todos

###

POST http://localhost:5000/api/todo/new
Content-Type: application/json

{
    "title":"new title"
}

###

DELETE http://localhost:5000/api/todo/delete/62e01723d8562f47e79b722e

###

PUT http://localhost:5000/api//todo/toggleStatus/62e018a8f812af9f3d867e04